"""add team_type to race

Revision ID: 0151f8961161
Revises: 2fda69a6c56b
Create Date: 2025-07-26 23:22:08.164196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0151f8961161'
down_revision: Union[str, None] = '2fda69a6c56b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('team_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'team_type')
    # ### end Alembic commands ###
