"""add team_type to race

Revision ID: 48a04e90cce7
Revises: 0151f8961161
Create Date: 2025-07-26 23:32:30.498119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48a04e90cce7'
down_revision: Union[str, None] = '0151f8961161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('races', sa.Column('coed_min_male', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('coed_min_female', sa.Integer(), nullable=True))
    op.add_column('races', sa.Column('registration_deadline', sa.DateTime(), nullable=False))
    op.add_column('races', sa.Column('entry_fee', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'entry_fee')
    op.drop_column('races', 'registration_deadline')
    op.drop_column('races', 'coed_min_female')
    op.drop_column('races', 'coed_min_male')
    # ### end Alembic commands ###
